[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
chain_id = 84532
optimizer = true
optimizer_runs = 200
verbosity = 3



[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
base_mainnet = { key = "${BASESCAN_API_KEY}" }

[fmt]
line_length = 100
indent_size = 4
bracket_spacing = true

[remappings]
"@openzeppelin/"="lib/openzeppelin-contracts/"
"@openzeppelin-contracts/"="lib/openzeppelin-contracts/contracts/"
"@solmate/"="lib/solmate/src/"
"@forge-std/"="lib/forge-std/src/"
